# This is a basic workflow to help you get started with Actions

name: GenFromJSON

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  list-json-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls SC22EVO/* | jq -R -s -c 'split("\n")[:-1]')"
        
  test-matrix:
    needs: list-json-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        json-file: ${{ fromJson(needs.list-json-files.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - run: cat ${{ matrix.json-file }}

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
          
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "squadracorsepolito/jsondbc"
          latest: true
          fileName: "jsondbc_Linux_x86_64.tar.gz"
          extract: true
          out-file-path: "jsondbc"
          
      - name: Print directory
        run: ls
          
      
